name: Push on Trunk

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    name: CI
    uses: AGES-RFID/cicd/.github/workflows/ci-dotnet.yml@main
    with:
      dotnet-version: "10.0.x"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-staging:
    name: CD Staging
    needs: [validate]
    uses: AGES-RFID/cicd/.github/workflows/deployment.yml@main
    with:
      environment: 'staging'
      version: ${{ github.sha }}
