name: Sync to GitLab

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  call-sync:
    uses: AGES-RFID/cicd/.github/workflows/sync-to-gitlab.yml@main
    secrets:
      gitlab_token: ${{ secrets.GITLAB_TOKEN }}